### ISSUE TITLE
Wrong blog post dates

### ISSUE THREAD

**Issue by zyplos** [2501CodeLab/Lane-Tech-NEO#1]
Dates on blog posts are completely wrong, but the posts are in right chronological order

**Comment by heymrhayes** [comment]
LOL.  You'll laugh too.  I often look for the more complex answer, but it's often simple.

I started looking into the moment.js documentation (if we're using that for other things, great, but we can do what we need with plain js.  If it's one-off for this page, I'd say lose it), but I didn't need to.

Here's your code:
`$(".news_date").text(fulldate.format("dddd, MMMM Do YYYY, h:mma"));`

You're using a class selector, so it's updating _all_ the "news_date" items with the value of whatever is the last item in the array.

**Comment by zyplos** [comment]
well that was silly

Fixed on all pages!
