### ISSUE TITLE
General contact form needs backend editing

### ISSUE THREAD

**Issue by zyplos** [2501CodeLab/Lane-Tech-NEO#6]
Currently does nothing at the moment

**Comment by heymrhayes** [comment]
Ugh.   This code is awful, with a lot of hard-coded email addresses for specific people, one of whom is no longer at Lane.

I'll put up a hack of the current version, but we might want to get rid of this;  I'll check with admins to see how many submissions we get from it.

But we definitely need to have a system for finding/removing certain names from the LT site.     We may also want to create some listing of contacts by name (i.e., an associative array) and have that in one file that we can easily maintain.  I often see obsolete information on the LT site.

**Comment by heymrhayes** [comment]
Made it prettier.

**Comment by zyplos** [comment]
Really nice new layout!
